export const ESPECIALIDADES = [
  "201 - Filosofía",
  "202 - Griego",
  "203 - Latín",
  "204 - Lengua Castellana y Literatura",
  "205 - Geografía e Historia",
  "206 - Matemáticas",
  "207 - Física y Química",
  "208 - Biología y Geología",
  "209 - Dibujo",
  "210 - Francés",
  "211 - Inglés",
  "212 - Alemán",
  "213 - Italiano",
  "221 - Música",
  "244 - Educación Física",
  "300 - Tecnología",
  "301 - Economía",
  "302 - Ámbito Científico-Tecnológico",
  "303 - Ámbito de Conocimiento Social",
  "308 - Formación y Orientación Laboral",
  "310 - Ámbito de Comunicación: Inglés",
  "320 - Ámbito de comunicación: Lengua Castellana y Literatura",
  "335 - Oficina de Proyectos de Fabricación Mecánica",
  "338 - Operaciones de Procesos",
  "339 - Máquinas, Servicios y Producción",
  "340 - Procesos de Gestión Administrativa",
  "342 - Procesos en la Industria Alimentaria",
  "343 - PIA Matadero y Carnicería-Charcutería",
  "344 - PIA Elaboración de Productos Lácteos",
  "345 - PIA Elaboración de Vinos y Otras Bebidas",
  "346 - Operaciones y Equipos de Producción Agraria",
  "347 - Oficina de Proyectos de Construcción",
  "348 - Instalaciones Electrotécnicas",
  "349 - Equipos Electrónicos",
  "351 - Tecnología de Puente",
  "352 - Sistemas y Aplicaciones Informáticas",
  "353 - Técnicas y procedimientos de Imagen y Sonido",
  "354 - Procesos Comerciales",
  "355 - Instalación y Mantenimiento de Equipos Térmicos y de Fluidos",
  "356 - Laboratorio",
  "357 - Procedimientos Sanitarios y Asistenciales",
  "358 - Servicios a la Comunidad",
  "359 - Procedimientos de Diagnóstico Clínico y Ortoprotésico",
  "360 - Administración de Empresas",
  "361 - Procesos de Producción Agraria",
  "362 - Procesos y Productos en Artes Gráficas",
  "363 - Organización y Procesos de Mantenimiento de Vehículos",
  "364 - Construcciones Civiles y Edificación",
  "365 - Sistemas Electrotécnicos y Automáticos",
  "366 - Sistemas Electrónicos",
  "367 - Hostelería y Turismo",
  "368 - Informática",
  "369 - Procesos y Medios de Comunicación",
  "370 - Procesos y Productos en Madera y Mueble",
  "371 - Procesos y Productos de Textil, Confección y Piel",
  "372 - Organización y Proyectos de Fabricación Mecánica",
  "373 - Organización y Gestión Comercial",
  "374 - Asesoría y Procesos de Imagen Personal",
  "375 - Organización y Proyectos de Sistemas Energéticos",
  "376 - Análisis y Química Industrial",
  "377 - Procesos Sanitarios",
  "378 - Intervención Sociocomunitaria",
  "380 - Procesos Diagnósticos Clínicos y Productos Ortoprotésicos",
  "391 - Navegación e Instalaciones Marinas",
  "443 - OEE Matadero y Carnicería-Charcutería",
  "444 - OEE Elaboración de Productos Lácteos",
  "445 - OEE Elaboración de Vinos y Otras Bebidas",
  "507 - Dibujo Técnico",
  "508 - Organización Industrial y Legislación",
  "509 - Dibujo Artístico y Color",
  "510 - Historia del Arte",
  "511 - Materiales y Tecnología: Diseño",
  "512 - Volumen",
  "513 - Diseño Gráfico",
  "514 - Diseño de Interiores",
  "515 - Medios Informáticos",
  "516 - Fotografía",
  "518 - Medios Audiovisuales",
  "522 - Diseño de Moda",
  "604 - Técnicas del Metal",
  "606 - Moldes y Reproducciones",
  "608 - Técnicas de Patronaje y Confección",
  "609 - Técnicas de Joyería y Bisutería",
  "610 - Técnicas Textiles",
  "617 - Técnicas Cerámicas",
  "618 - Ebanistería Artística",
  "619 - Fotografía y Procesos de Reproducción",
  "620 - Modelismo y Maquetismo",
  "650 - Producción de Artes Gráficas",
  "651 - Mantenimiento de Vehículos",
  "652 - Fabricación e Instalación de Carpintería y Mueble",
  "653 - Patronaje y Confección",
  "654 - Soldadura",
  "655 - Peluquería",
  "656 - Mecanizado y Mantenimiento de Máquinas",
  "657 - Estética",
  "658 - Servicios de Restauración",
  "659 - Cocina y Pastelería",
  "701 - Francés (E.O.I.)",
  "702 - Inglés (E.O.I.)",
  "703 - Alemán (E.O.I.)",
  "704 - Italiano (E.O.I.)",
  "705 - Español para Extranjeros (E.O.I.)",
  "706 - Chino (E.O.I.)",
  "707 - Ruso (E.O.I.)",
  "708 - Árabe (E.O.I.)",
  "910 - Orientación Educativa"
];